### ISSUE TITLE
Lib Magick++ outdated

### ISSUE THREAD

**Issue by Teufelchen1** [HorstBaerbel/GBA-image-tools#1]
Hi,

just a heads-up; In this [commit](https://github.com/ImageMagick/ImageMagick/commit/018189d8b8f6797251dd12dbeb83382a17814bfc), `luminosity` got renamed to `lightness`, breaking your code.

**Comment by HorstBaerbel** [comment]
Thanks for the info. I'm currently working on a big refactor removing ImageMagick as much as possible except for reading images. Might replace that by stb_ libraries in the future too.

**Comment by HorstBaerbel** [comment]
Should work with ImageMagick 7 now
